package com.yh.st.base.domain;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Role extends Entity {

	private static final long serialVersionUID = 8555191684453284507L;
	private String name;

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

}